variable "instance_type" {}
variable "instance_name" {}
variable "key" {}
variable "ami" {}
variable "vpc_cidr" {}
variable "public_sub_cidr" {}
variable "prisub_cidr" {}
variable "az_1" {}
variable "vpc_name" {}
variable "eip_name" {}
variable "igw_name" {}
variable "cluster_name" {}
variable "kubernetes_version" {}
variable "node_role_name" {}
variable "cluster_role_name" {}
variable "subnet_id" {}
variable "eks_sg_id" {}
variable "node_sg_id" {}
variable "vpc_id" {}
variable "az_2" {}
variable "public_sub2_cidr" {}